name: fibrosis_pulmonar_env
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - pandas
  - scikit-learn
  - lightgbm
  - pillow
  - pydicom
  - imageio
  - fastai
  - pytorch
  - torchvision
  - gradio